# Generated by Django 4.0.4 on 2022-06-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='econtact',
        ),
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
