# Generated by Django 4.0.4 on 2022-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_remove_signup_id_alter_signup_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=42)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loginform',
            },
        ),
    ]
